name: Deploy EC2

on:
  workflow_call:

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Baixar artefato do build
      uses: actions/download-artifact@v4
      with:
        name: programa

    - name: Upload dos arquivos para o servidor
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "./main"
        target: "/home/${{ secrets.REMOTE_USER }}/"

    - name: Executar comandos remotos via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export HOST=${{ secrets.DBHOST }}
          export USER=${{ secrets.DBUSER }}
          export PASSWORD=${{ secrets.DBPASSWORD }}
          export DBNAME=${{ secrets.DBNAME }}
          export DBPORT=${{ secrets.DBPORT }}
          export PORT=8000

          cd /home/${{ secrets.REMOTE_USER }}
          chmod +x main

          # Matar processos antigos da aplicação, se houver
          pkill -f "./main" || true

          # Iniciar aplicação em segundo plano
          nohup ./main > nohup.out 2> nohup.err < /dev/null &
