name: Entrega continua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition tarefa_api-go --query taskDefinition > task-definition.json
