name: Kubernetes

on:
  workflow_call:

jobs:
  EKS:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-west-2

    - run: git clone https://github.com/alissonmuniz17/Infra_CI_Kubernetes.git

    - name: Instalando Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Init Terraform
      run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init -upgrade

    - name: Destroy Terraform
      run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog destroy -auto-approve

    - name: Apply Terraform
      run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve

    - name: Instalando o Kubectl
      uses: Azure/setup-kubectl@v4.0.0

    - name: Criando um arquivo kubeconfig
      run: aws sts get-caller-identity

    - name: Criar arquivo kubeconfig automaticamente
      run: aws eks update-kubeconfig --region us-west-2 --name homolog2

    - name: Testando a configuração
      run: kubectl get svc
      
